[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
# startCommand = "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"
healthcheckPath = "/health"
healthcheckTimeout = 300
port = 8080

[deploy.env]
APP_NAME = "Lifespan"
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://beta.lifespan.dev"
ASSET_URL = "https://beta.lifespan.dev"
APP_KEY = "base64:b9s0KnR3GhoY1oz5r0OAPoYb5qfDziovEqzyxHWHA1E="
APP_TIMEZONE = "Europe/London"
APP_LOCALE = "en_GB"

# Database Configuration
# Note: These settings provide a fallback if Railway's auto-injection fails
DB_CONNECTION = "pgsql"
DB_HOST = "lifespan_db.railway.internal"
DB_PORT = "5432"
DB_DATABASE = "railway"
DB_USERNAME = "postgres"
# DB_PASSWORD is intentionally not set here as it should be set as a secret variable
# in Railway's dashboard, or automatically injected by the linked PostgreSQL service

# Logging and Debug Configuration
LOG_CHANNEL = "stack"
LOG_LEVEL = "debug"
BROADCAST_DRIVER = "log"
CACHE_DRIVER = "file"
FILESYSTEM_DISK = "local"
QUEUE_CONNECTION = "sync"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "525600"

# Railway configuration will automatically inject additional variables
# for any linked PostgreSQL service, including the database password

# Railway-specific upload configuration
# These variables help Railway understand our upload requirements
RAILWAY_UPLOAD_SIZE_LIMIT = "100M"
RAILWAY_REQUEST_TIMEOUT = "300" 