[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "docker/prod/entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
APP_NAME = "Lifespan"
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stack"
BROADCAST_DRIVER = "log"
CACHE_DRIVER = "file"
FILESYSTEM_DISK = "local"
QUEUE_CONNECTION = "sync"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "525600"

# Database configuration will be automatically injected by Railway
# when you add a PostgreSQL service and link it to this service 