[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/local/bin/entrypoint.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.env]
APP_NAME = "Lifespan"
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://lifespan-beta.up.railway.app"
APP_KEY = "base64:b9s0KnR3GhoY1oz5r0OAPoYb5qfDziovEqzyxHWHA1E="
APP_TIMEZONE = "Europe/London"
APP_LOCALE = "en_GB"

# Database configuration will be automatically injected by Railway
# when a PostgreSQL service is linked 