[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
startCommand = ""
healthcheckPath = "/health"
healthcheckTimeout = 300
port = 8080

[deploy.env]
APP_NAME = "Lifespan"
APP_ENV = "production"
APP_DEBUG = "false"
APP_URL = "https://lifespan-beta-production.up.railway.app"
ASSET_URL = "https://lifespan-beta-production.up.railway.app"
APP_KEY = "base64:b9s0KnR3GhoY1oz5r0OAPoYb5qfDziovEqzyxHWHA1E="
APP_TIMEZONE = "Europe/London"
APP_LOCALE = "en_GB"

# Logging and Debug Configuration
LOG_CHANNEL = "stack"
LOG_LEVEL = "debug"
BROADCAST_DRIVER = "log"
CACHE_DRIVER = "file"
FILESYSTEM_DISK = "local"
QUEUE_CONNECTION = "sync"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "525600"

# Database configuration will be automatically injected by Railway
# when a PostgreSQL service is linked 