services:
  - type: web
    name: lifespan-beta
    env: docker
    dockerfilePath: render.Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: storage
      mountPath: /var/www/storage
      sizeGB: 1
    envVars:
      - key: APP_NAME
        value: Lifespan
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://lifespan-beta.onrender.com
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: debug
      - key: DB_CONNECTION
        value: pgsql
      - key: RAILWAY_PRIVATE_DOMAIN
        fromDatabase:
          name: lifespan_db
          property: privateDomain
      - key: DATABASE_URL
        fromDatabase:
          name: lifespan_db
          property: connectionString
      - key: DATABASE_PUBLIC_URL
        fromDatabase:
          name: lifespan_db
          property: publicUrl
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 120
      - key: MEMCACHED_HOST
        value: 127.0.0.1
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PASSWORD
        value: null
      - key: REDIS_PORT
        value: 6379
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: mailpit
      - key: MAIL_PORT
        value: 1025
      - key: MAIL_USERNAME
        value: null
      - key: MAIL_PASSWORD
        value: null
      - key: MAIL_ENCRYPTION
        value: null
      - key: MAIL_FROM_ADDRESS
        value: hello@example.com
      - key: MAIL_FROM_NAME
        value: "${APP_NAME}"
      - key: AWS_ACCESS_KEY_ID
        value: null
      - key: AWS_SECRET_ACCESS_KEY
        value: null
      - key: AWS_DEFAULT_REGION
        value: us-east-1
      - key: AWS_BUCKET
        value: null
      - key: AWS_USE_PATH_STYLE_ENDPOINT
        value: false
      - key: PUSHER_APP_ID
        value: null
      - key: PUSHER_APP_KEY
        value: null
      - key: PUSHER_APP_SECRET
        value: null
      - key: PUSHER_HOST
        value: null
      - key: PUSHER_PORT
        value: null
      - key: PUSHER_SCHEME
        value: null
      - key: PUSHER_APP_CLUSTER
        value: mt1
      - key: VITE_APP_NAME
        value: "${APP_NAME}"
      - key: VITE_PUSHER_APP_KEY
        value: "${PUSHER_APP_KEY}"
      - key: VITE_PUSHER_HOST
        value: "${PUSHER_HOST}"
      - key: VITE_PUSHER_PORT
        value: "${PUSHER_PORT}"
      - key: VITE_PUSHER_SCHEME
        value: "${PUSHER_SCHEME}"
      - key: VITE_PUSHER_APP_CLUSTER
        value: "${PUSHER_APP_CLUSTER}"

databases:
  - name: lifespan_db
    databaseName: railway
    user: postgres
    plan: free 