services:
  - type: web
    name: lifespan-beta
    env: docker
    dockerfilePath: render.Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: Lifespan
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: lifespan-beta
          property: host
      - key: LOG_CHANNEL
        value: stack
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: lifespan_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: lifespan_db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: lifespan_db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: lifespan_db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: lifespan_db
          property: password
      - key: BROADCAST_DRIVER
        value: log
      - key: CACHE_DRIVER
        value: file
      - key: FILESYSTEM_DISK
        value: local
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: SESSION_LIFETIME
        value: 525600

databases:
  - name: lifespan_db
    databaseName: lifespan
    user: lifespan
    plan: free 