services:
  - type: web
    name: lifespan-beta
    env: docker
    dockerfilePath: ./Dockerfile.prod
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        fromService:
          type: web
          name: lifespan-beta
          property: url
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: lifespan_beta
          property: host
      - key: DB_PORT
        fromDatabase:
          name: lifespan_beta
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: lifespan_beta
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: lifespan_beta
          property: username
      - key: DB_PASSWORD
        fromDatabase:
          name: lifespan_beta
          property: password
    healthCheckPath: /
    autoDeploy: true

databases:
  - name: lifespan-db
    databaseName: lifespan_beta
    user: lifespan_user
    plan: free 