<?php

return [
    'models_namespace' => 'App\\Models',
    'controllers_namespace' => 'App\\Http\\Controllers',
    'requests_namespace' => 'App\\Http\\Requests',
    'resources_namespace' => 'App\\Http\\Resources',
    'seeders_namespace' => 'Database\\Seeders',
    'factories_namespace' => 'Database\\Factories',
    'tests_namespace' => 'Tests',
    'views_namespace' => 'resources/views',
    'routes_namespace' => 'routes',
    'migrations_namespace' => 'database/migrations',
    'models_path' => 'app/Models',
    'controllers_path' => 'app/Http/Controllers',
    'requests_path' => 'app/Http/Requests',
    'resources_path' => 'app/Http/Resources',
    'seeders_path' => 'database/seeders',
    'factories_path' => 'database/factories',
    'tests_path' => 'tests',
    'views_path' => 'resources/views',
    'routes_path' => 'routes',
    'migrations_path' => 'database/migrations',
    'generators' => [
        'model' => Blueprint\Generators\ModelGenerator::class,
        'controller' => Blueprint\Generators\ControllerGenerator::class,
        'request' => Blueprint\Generators\RequestGenerator::class,
        'resource' => Blueprint\Generators\ResourceGenerator::class,
        'seeder' => Blueprint\Generators\SeederGenerator::class,
        'factory' => Blueprint\Generators\FactoryGenerator::class,
        'test' => Blueprint\Generators\TestGenerator::class,
        'view' => Blueprint\Generators\ViewGenerator::class,
        'route' => Blueprint\Generators\RouteGenerator::class,
        'migration' => Blueprint\Generators\MigrationGenerator::class,
    ],
    'templates' => [
        'model' => 'blueprint/templates/model.stub',
        'controller' => 'blueprint/templates/controller.stub',
        'request' => 'blueprint/templates/request.stub',
        'resource' => 'blueprint/templates/resource.stub',
        'seeder' => 'blueprint/templates/seeder.stub',
        'factory' => 'blueprint/templates/factory.stub',
        'test' => 'blueprint/templates/test.stub',
        'view' => 'blueprint/templates/view.stub',
        'route' => 'blueprint/templates/route.stub',
        'migration' => 'blueprint/templates/migration.stub',
    ],
    'generation' => [
        'model' => true,
        'controller' => true,
        'request' => true,
        'resource' => true,
        'seeder' => true,
        'factory' => true,
        'test' => true,
        'view' => true,
        'route' => true,
        'migration' => true,
    ],
    'formatting' => [
        'indent' => '    ',
        'line_ending' => PHP_EOL,
    ],
    'production' => [
        'enabled' => true,
        'cache' => true,
        'optimize' => true,
    ],
]; 